name: "Vprofile IAC"
on:
  push:
    branches:
      - main
      - stage
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**
      
env:
#credentials for AWS
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
AWS_REGION: us-east-1
EKS_CLUSTER: vprofile-eks  

jobs:
  terraform:
    name: "APPLY terraform code changes"
    runs on: ubuntu-latest
    defaults: 
      run:
        shell:
        working-directory: ./terraform
      
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: terraform init
      id: init
      run: terraform init -backend-config="$BUCKET_TF_STATE"
      
      
    - name: terraform format
      id: fmt 
      run: terraform fmt -check
      
    - name: terraform validate
      id: validate
      run: terraform validate  
    
      
    - name: terraform plan
      id: plan
      run: terraform plan -no-color -input=false -out planfile
      continue-on-error: true

    - name: terraform plan status
      if: steps.plan.outcome == 'failure'
      run: exit 2